### ISSUE TITLE
Q: docker run prints nothing to console

### ISSUE THREAD

**Issue by mloskot** [DataGrip/docker-env-oracle#1]
First, thanks a lot for the trimmed sub-1GB image with the Oracle database!

I'm fairly new to docker still cutting my way through the docs so this may be a trivial question, sorry.

I'm running it with the latest Docker for Windows on Windows 10

```
c:\> docker run -d -p 8080:8080 -p 1521:1521 datagrip/oracle:11.2
dfabda745c715c776957691167a3380dadeb8fae5093364ea16d5e2eaca20f14
```

and it seems to work well, connectivity is fine

```
C:\> docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                                            NAMES
dfabda745c71        datagrip/oracle:11.2   "/entrypoint.sh"    3 minutes ago       Up 3 minutes        0.0.0.0:1521->1521/tcp, 0.0.0.0:8080->8080/tcp   happy_bohr
```

I'm just curious `docker run` does not print any diagnostics, is it supposed not to?
Shouldn't the [entrypoint.sh](https://github.com/DataGrip/docker-env-oracle/blob/master/11.2/entrypoint.sh) initialization messages be sent to console?

**Comment by tjlee** [comment]
> I'm just curious docker run does not print any diagnostics, is it supposed not to?
What kind of diagnostic information do you expect?

At the moment container writes logs to logs output:
![image](https://user-images.githubusercontent.com/1133087/62279289-754fe900-b452-11e9-93fc-5cb1ab1fccfb.png)

More information in [official documentation](https://docs.docker.com/engine/reference/commandline/logs/)
